blank_issues_enabled: false
contact_links:
  - name: No Contributions Accepted
    url: https://github.com/matteoespo/docuquery-rag-agent/blob/main/CONTRIBUTING.md
    about: This is a personal project. I do not accept any issues, bug reports, or feature requests.
