name: Dependabot Auto-Merge

on: pull_request

permissions:
  contents: write
  pull-requests: write

jobs:
  dependabot:
    runs-on: ubuntu-latest
    if: github.actor == 'dependabot[bot]'
    steps:
      - name: Dependabot metadata
        id: metadata
        uses: dependabot/fetch-metadata@v2
        with:
          github-token: "${{ secrets.GITHUB_TOKEN }}"
          
      - name: Inject Co-author and Enable Auto-merge
        run: |
          # Fetch the current PR body
          PR_BODY=$(gh pr view "$PR_URL" --json body -q .body)
          
          # Update the PR body to include the co-author so you get the contribution badge
          gh pr edit "$PR_URL" --body "$PR_BODY
          
          Co-authored-by: matteoespo <matteoespositomarroccella@gmail.com>"
          
          # Approve and enable auto-merge (using squash to ensure the body goes into the commit message)
          gh pr review --approve "$PR_URL"
          gh pr merge --auto --squash "$PR_URL"
        env:
          PR_URL: ${{github.event.pull_request.html_url}}
          GH_TOKEN: ${{secrets.GITHUB_TOKEN}}
